### ISSUE TITLE
plotTree needs improvement

### ISSUE THREAD

**Issue by benRenard** [Felipemendezrios/RatingShiftHappens#10]
Main problem: nodes can overplot the way the function was coded. A quickfix was implemented in commit  d00d3e4 so that all nodes can at least be seen, but it's still not very nice. The function needs to be recoded, I can see 2 options:
1. compute coordinates by travelling the tree upward (i.e. from terminal nodes to node 0), rather than downward as currently implemented. 
2. try a polar plot, where node 0 would be at radius 0, level-1 nodes at radius 1 and evenly-spaced angles, etc.

**Comment by Felipemendezrios** [comment]
plotTree has been modified in commit: 07dbb5a.

Update tree structure plot :
- Plot node level by level
- Assign an axis reference to plot nodes
- Axis reference can move level by level depending on the number of children on the left or on the right
- Plot node using point and text instead of label

Feel free to reopen the issue if necessary.
